server:
  port: 9002

resilience4j:
  ratelimiter:
    instances:
      basicExample:
        # request di qua
        limitForPeriod: 2
        # trong 10s
        limitRefreshPeriod: 3s
        # thời gian requet tiếp theo vào đợi là 5s
        timeoutDuration: 1s


